<?php


namespace MainBundle\Repository;
/**
 * EventsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class EventsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByName($name)
    {
        return $this->createQueryBuilder('t')
            ->andWhere('t.nomEvent LIKE :name')
            ->setParameter('name', '%' . $name . '%')
            ->getQuery()
            ->getResult();
    }
}