<?php

namespace MainBundle\Repository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function firstJoin($id)
    {
        $em= $query=$this->getEntityManager();
        $RAW_QUERY = "SELECT * FROM reservation r JOIN events e ON r.id_ev =: e.id_ev WHERE r.id_par=: idt  ";
        $statement=$em->getConnection()->prepare($RAW_QUERY);

        $statement->bindValue('idt',$id);
        $statement->execute();
        return $statement;




    }
}


