<?php

namespace ForumBundle\Repository;

/**
 * CommentairePostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentairePostRepository extends \Doctrine\ORM\EntityRepository
{
}
