<?php

namespace ForumBundle\Repository;

/**
 * Likes_DislikesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Likes_DislikesRepository extends \Doctrine\ORM\EntityRepository
{
}
